### ISSUE TITLE
Tweaks to current UI

### ISSUE THREAD

**Issue by onggunhao** [enabledao/enable-ui#28]
Some thoughts after looking at the UI more closely. 

## 1: Missing "Contributing Lenders" section

![image](https://user-images.githubusercontent.com/518024/62414757-a0a12680-b652-11e9-825e-5f740dd79482.png)

## 2: Contributing Lenders don't have avatars

* Ethereum addresses do not have avatars

![image](https://user-images.githubusercontent.com/518024/62414724-0b059700-b652-11e9-8864-238b80764110.png)

## 3: Missing "Social Credit" section

* Our survey showed that 80+% of people would be more confident to donate if a borrower had people to "guarantor" or "socially attest" for borrower
* I can be listed as a guarantor, while others can "socially attest" for Ines (we can hard-code this for now)

![image](https://user-images.githubusercontent.com/518024/62414918-7d777680-b654-11e9-972f-d97aeec81c6c.png)

## 4. Typography - line length

![image](https://user-images.githubusercontent.com/518024/62415071-b57fb900-b656-11e9-87cb-50dfa1a9d83f.png)

![image](https://user-images.githubusercontent.com/518024/62414987-81f05f00-b655-11e9-8779-3a01e4f2c407.png)

![image](https://user-images.githubusercontent.com/518024/62415009-dabff780-b655-11e9-9fe7-d87a4e5d83d9.png)

https://practicaltypography.com/line-length.html

## 5. Typography - paragraph spacing and line height

![image](https://user-images.githubusercontent.com/518024/62415104-1effc780-b657-11e9-8be3-7a1b92dbc5c4.png)

https://pearsonified.com/golden-ratio-typography-intro/

## 6. Typography - letter-spacing

![image](https://user-images.githubusercontent.com/518024/62415192-486d2300-b658-11e9-9fdf-f651ba88a02f.png)

**Comment by nczhu** [comment]
A few UX comments as a potential donor looking through these designs, mostly around what will get me to actually give you money:

1. The color themes should be blue (green buttons), it conveys more trust and professionalism. The designs on the left, while pretty, look more like a paper flyer / advertisement. I am less likely to give the website on the left money, because it doesn't look trustworthy. 

2. I like featuring the video at the top. But it needs to be a rectangle video player. It needs to look like an obvious video player. 

3. The information density should be higher. The hero is pretty but takes up too much space. This is an investment page. Investments pages are very information dense above the fold. 

I want to see as much information, numbers, data that tells me "this is not a scam" as possible. The more pretty, showy, this page tries to impress me, the less likely I'll donate. I want to see a higher density of numbers, and **other trust signals**.
