### ISSUE TITLE
Look into why loan constants have delay (desktop) or do not render (mobile)

### ISSUE THREAD

**Issue by onggunhao** [enabledao/enable-ui#69]
Currently, there are 2 issues:

* On desktop, there is a ~1 second delay between the time when the initial values (i.e. 0) load, and when they load the constants

* On my mobile phone (on dev site), the constant values do not load (i.e. show 0)

These are not due to Infura, as these are all loan constants. Currently, we return them in `metadata.js`. 

- [ ] Should we refactor and move all loan constants into one file? (consider `config/ines.fund.js`)
- [ ] Should we just use constants, instead of `fetchLoanMetadata` in `metadata.js` (we can replace these with getter functions in the future, but it is likely that most of these will be stored in databases + IPFS, and not on-chain)

**Comment by adibas03** [comment]
The lag, is not from the constants, but instead from the data loaded from the smart contract, as that is part of the data needed to display the required information.
For the mobile view, the data looks to load correctly. @onggunhao did you change to kovan to access the page?
Since we have only Kovan data set up?
Sorry I couldn't do anything yesterday,
Will be up in about 2 hours
